version: '3'

services:
  app:
    image: remindmeal/remindmeal:latest
    expose:
      - 9001
    networks: 
      - web
      - db
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  db:
    image: postgres:13
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - db
    env_file:
      - .env
  web:
    image: nginx:latest
    volumes:
      - /home/debian/remindmeal-config/nginx/:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt
    networks:
      - web
    ports:
      - 80:80
      - 443:443

volumes:
  data:

networks:
  web:
  db:
