using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace RemindMeal.Migrations
{
    public partial class Test : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
ALTER TABLE ""Recipes"" ALTER COLUMN ""Id"" TYPE integer;
ALTER TABLE ""Recipes"" ALTER COLUMN ""Id"" SET NOT NULL;
ALTER SEQUENCE ""Recipes_Id_seq"" RENAME TO ""Recipes_Id_old_seq"";
ALTER TABLE ""Recipes"" ALTER COLUMN ""Id"" DROP DEFAULT;
ALTER TABLE ""Recipes"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval('""Recipes_Id_seq""', nextval('""Recipes_Id_old_seq""'), false);
DROP SEQUENCE ""Recipes_Id_old_seq"";

ALTER TABLE ""Meals"" ALTER COLUMN ""Id"" TYPE integer;
ALTER TABLE ""Meals"" ALTER COLUMN ""Id"" SET NOT NULL;
ALTER SEQUENCE ""Meals_Id_seq"" RENAME TO ""Meals_Id_old_seq"";
ALTER TABLE ""Meals"" ALTER COLUMN ""Id"" DROP DEFAULT;
ALTER TABLE ""Meals"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval('""Meals_Id_seq""', nextval('""Meals_Id_old_seq""'), false);
DROP SEQUENCE ""Meals_Id_old_seq"";

ALTER TABLE ""Friends"" ALTER COLUMN ""Id"" TYPE integer;
ALTER TABLE ""Friends"" ALTER COLUMN ""Id"" SET NOT NULL;
ALTER SEQUENCE ""Friends_Id_seq"" RENAME TO ""Friends_Id_old_seq"";
ALTER TABLE ""Friends"" ALTER COLUMN ""Id"" DROP DEFAULT;
ALTER TABLE ""Friends"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval('""Friends_Id_seq""', nextval('""Friends_Id_old_seq""'), false);
DROP SEQUENCE ""Friends_Id_old_seq"";

ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""Id"" TYPE integer;
ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""Id"" SET NOT NULL;
ALTER SEQUENCE ""AspNetUserClaims_Id_seq"" RENAME TO ""AspNetUserClaims_Id_old_seq"";
ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""Id"" DROP DEFAULT;
ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval('""AspNetUserClaims_Id_seq""', nextval('""AspNetUserClaims_Id_old_seq""'), false);
DROP SEQUENCE ""AspNetUserClaims_Id_old_seq"";

ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""Id"" TYPE integer;
ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""Id"" SET NOT NULL;
ALTER SEQUENCE ""AspNetRoleClaims_Id_seq"" RENAME TO ""AspNetRoleClaims_Id_old_seq"";
ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""Id"" DROP DEFAULT;
ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval('""AspNetRoleClaims_Id_seq""', nextval('""AspNetRoleClaims_Id_old_seq""'), false);
DROP SEQUENCE ""AspNetRoleClaims_Id_old_seq"";
"
            );
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Recipes",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Meals",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Friends",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "AspNetUserClaims",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "AspNetRoleClaims",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
